#### IRIS Dataset Example

How to Correctly add labels back to the original dataframe

Use this for HG002 analysis

In [1]:
"""
Imports
"""
import pandas as pd
import numpy as np
from fancyimpute import KNN
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import LeaveOneOut
from scipy.stats import ks_2samp
from scipy import stats
from matplotlib import pyplot
from sklearn import preprocessing
from scipy.linalg import svd
from sklearn.decomposition import TruncatedSVD
import sqlite3
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA as sklearnPCA
import plotly.plotly as py
from sklearn.cluster import DBSCAN
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import f1_score, precision_score
from sklearn import preprocessing
from ggplot import *
from bokeh.charts import TimeSeries
from bokeh.models import HoverTool
from bokeh.plotting import show
from bokeh.charts import Scatter, Histogram, output_file, show
from bokeh.plotting import figure, show, output_file, ColumnDataSource
from bokeh.io import output_notebook
from bokeh.charts import Bar, output_file, show
import bokeh.palettes as palettes
from bokeh.models import HoverTool, BoxSelectTool, Legend
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection)

/Users/lmc2/anaconda/envs/NIHFAES/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

/Users/lmc2/anaconda/envs/NIHFAES/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.



In [76]:
df = pd.read_csv('/Users/lmc2/iris.csv')

In [77]:
label_encoder = preprocessing.LabelEncoder()
df['species'] = label_encoder.fit_transform(df['species'])

In [78]:
Y = pd.DataFrame()
Y['species'] = df['species']

In [79]:
X = pd.DataFrame(df)
X=X[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

In [80]:
scaler=preprocessing.StandardScaler()
X=scaler.fit_transform(X)

In [81]:
# Train Test Split
# Train on 70% of the data and test on 30%
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.7, random_state=0)
# Train Random Forest Classifier
model = RandomForestClassifier() 
model.fit(X_train, y_train)

/Users/lmc2/anaconda/envs/NIHFAES/lib/python3.5/site-packages/ipykernel/__main__.py:6: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [82]:
pred = model.predict(X_test)
precision_score(pred, y_test, average='micro') 

0.92380952380952386

In [83]:
# How to add labels back to the original dataframe
ytest = pd.DataFrame()
predt = pd.DataFrame()

ytest['ytest'] = y_test
predt['pred'] = pred
ytest['y_test'] = label_encoder.inverse_transform(y_test)
ytest['pred_test'] = label_encoder.inverse_transform(pred)

ytest.head()

ytest      y_test   pred_test
0    NaN   virginica   virginica
1    0.0  versicolor  versicolor
2    0.0      setosa      setosa
3    0.0   virginica   virginica
4    0.0      setosa      setosa

In [84]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        33
          1       0.81      1.00      0.89        34
          2       1.00      0.79      0.88        38

avg / total       0.94      0.92      0.92       105



In [85]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

[[33  0  0]
 [ 0 34  0]
 [ 0  8 30]]


http://scikit-learn.org/stable/tutorial/statistical_inference/putting_together.html

https://www.datacamp.com/community/blog/scikit-learn-cheat-sheet#gs.oyP2toM

In [86]:
# pred == y_test

In [87]:
xtest = pd.DataFrame(X_test)

all1 = pd.concat([xtest, ytest], axis=1)

In [88]:
all1.head()

0         1         2         3  ytest      y_test   pred_test
0 -0.052506 -0.592373  0.762758  1.580464    NaN   virginica   virginica
1  0.189830 -1.973554  0.137547 -0.262387    0.0  versicolor  versicolor
2 -0.416010  2.630382 -1.340227 -1.315444    0.0      setosa      setosa
3  1.765012 -0.362176  1.444807  0.790671    0.0   virginica   virginica
4 -1.021849  0.788808 -1.283389 -1.315444    0.0      setosa      setosa

In [90]:
pd.value_counts(all1['y_test'].values, sort=False)

versicolor    34
virginica     38
setosa        33
dtype: int64

In [89]:
all1.to_csv('all_2.csv', index=False)