### GTconswithoutXX Label Summary

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from scipy import stats
from sklearn import metrics
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix

In [2]:
df_train = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/training_data/EM_HR_IC_HG002_all_tech.csv')
df_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/all/DEL/5k_HG002_all_tech.csv')

In [3]:
Ill250_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/tech_sep/DEL/HG002/250bp_HG002_DEL_min1.csv')
Ill300_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/tech_sep/DEL/HG002/300x_HG002_DEL_min1.csv')
IllMP_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/tech_sep/DEL/HG002/MP_HG002_DEL_min1.csv')
PB_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/tech_sep/DEL/HG002/PB_HG002_DEL_min1.csv')
TenX_test = pd.read_csv('/Volumes/lesleydata/SVanalyzer_ML/Oct122017_Revised_R/dataframes/test/final_df/tech_sep/DEL/HG002/TenX_HG002_DEL_min1.csv')

In [4]:
GTcons = Ill250_test['GTcons']
GTwithout = Ill250_test['GTconswithoutIll250.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 853    0    0]
 [   0 2194    0]
 [   0    0  781]]


In [5]:
GTcons = Ill300_test['GTcons']
GTwithout = Ill300_test['GTconswithoutIll300x.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 871    0    0]
 [   0 2162    0]
 [   0    0  912]]


In [6]:
GTcons = IllMP_test['GTcons']
GTwithout = IllMP_test['GTconswithoutIllMP.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 879    0    0]
 [   0 2240    0]
 [   0    0  911]]


In [7]:
GTcons = TenX_test['GTcons']
GTwithout = TenX_test['GTconswithoutTenX.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 865    0    0]
 [   0 2240    0]
 [   0    0  898]]


In [8]:
GTcons = PB_test['GTcons']
GTwithout = PB_test['GTconswithoutpacbio.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 788    0    0]
 [   0 1812    0]
 [   0    0  681]]


**Training Data**

In [9]:
GTcons = df_train['GTcons']
GTwithout = df_train['GTconswithoutIll250.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 374    6   61    3]
 [  24 1454    0    0]
 [  16    0  822    0]
 [  41    0    0  189]]


In [10]:
GTcons = df_train['GTcons']
GTwithout = df_train['GTconswithoutIll300x.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 402    8   19   15]
 [  15 1463    0    0]
 [  22    0  816    0]
 [   2    0    0  228]]


In [11]:
GTcons = df_train['GTcons']
GTwithout = df_train['GTconswithoutIllMP.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 426    5   13    0]
 [   2 1476    0    0]
 [   1    0  837    0]
 [   0    0    0  230]]


In [12]:
GTcons = df_train['GTcons']
GTwithout = df_train['GTconswithoutTenX.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 421    0   22    1]
 [  21 1457    0    0]
 [   0    0  838    0]
 [   7    0    0  223]]


In [13]:
GTcons = df_train['GTcons']
GTwithout = df_train['GTconswithoutpacbio.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 263  143   26   12]
 [  90 1388    0    0]
 [ 212    0  626    0]
 [  71    0    0  159]]


In [14]:
df_train['GTcons'].replace(-1, 'Unknown', inplace=True)
df_train['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_train['GTconswithoutIll250.GT'].replace(-1, 'Unknown', inplace=True)
df_train['GTconswithoutIll250.GT'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTconswithoutIll250.GT'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTconswithoutIll250.GT'].replace(2, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTwithout'], margins=True)

GTwithout              -1     0    1    2   All
GTcons                                         
Heterozygous_Variant  212     0  626    0   838
Homozygous_Reference   90  1388    0    0  1478
Homozygous_Variant     71     0    0  159   230
Unknown               263   143   26   12   444
All                   636  1531  652  171  2990

In [17]:
df_train['GTcons'].replace(-1, 'Unknown', inplace=True)
df_train['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_train['GTconswithoutIll300x.GT'].replace(-1, 'Unknown', inplace=True)
df_train['GTconswithoutIll300x.GT'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTconswithoutIll300x.GT'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTconswithoutIll300x.GT'].replace(2, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTwithout'], margins=True)

GTwithout              -1     0    1    2   All
GTcons                                         
Heterozygous_Variant  212     0  626    0   838
Homozygous_Reference   90  1388    0    0  1478
Homozygous_Variant     71     0    0  159   230
Unknown               263   143   26   12   444
All                   636  1531  652  171  2990

In [18]:
df_train['GTcons'].replace(-1, 'Unknown', inplace=True)
df_train['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_train['GTconswithoutIllMP.GT'].replace(-1.0, 'Unknown', inplace=True)
df_train['GTconswithoutIllMP.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_train['GTconswithoutIllMP.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_train['GTconswithoutIllMP.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout          -1     0    1    2   All
GTcons                                         
Heterozygous_Variant  212     0  626    0   838
Homozygous_Reference   90  1388    0    0  1478
Homozygous_Variant     71     0    0  159   230
Unknown               263   143   26   12   444
All                   636  1531  652  171  2990

In [21]:
df_train['GTcons'].replace(-1, 'Unknown', inplace=True)
df_train['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_train['GTconswithoutTenX.GT'].replace(-1.0, 'Unknown', inplace=True)
df_train['GTconswithoutTenX.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_train['GTconswithoutTenX.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_train['GTconswithoutTenX.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout         Heterozygous_Variant  Homozygous_Reference  \
GTcons                                                             
Heterozygous_Variant                   626                     0   
Homozygous_Reference                     0                  1388   
Homozygous_Variant                       0                     0   
Unknown                                 26                   143   
All                                    652                  1531   

GTconswithout         Homozygous_Variant  Unknown   All  
GTcons                                                   
Heterozygous_Variant                   0      212   838  
Homozygous_Reference                   0       90  1478  
Homozygous_Variant                   159       71   230  
Unknown                               12      263   444  
All                                  171      636  2990

In [20]:
df_train['GTcons'].replace(-1, 'Unknown', inplace=True)
df_train['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_train['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_train['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_train['GTconswithoutpacbio.GT'].replace(-1.0, 'Unknown', inplace=True)
df_train['GTconswithoutpacbio.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_train['GTconswithoutpacbio.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_train['GTconswithoutpacbio.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout         Heterozygous_Variant  Homozygous_Reference  \
GTcons                                                             
Heterozygous_Variant                   626                     0   
Homozygous_Reference                     0                  1388   
Homozygous_Variant                       0                     0   
Unknown                                 26                   143   
All                                    652                  1531   

GTconswithout         Homozygous_Variant  Unknown   All  
GTcons                                                   
Heterozygous_Variant                   0      212   838  
Homozygous_Reference                   0       90  1478  
Homozygous_Variant                   159       71   230  
Unknown                               12      263   444  
All                                  171      636  2990

** Test Set **

In [22]:
GTcons = df_test['GTcons']
GTwithout = df_test['GTconswithoutIll250.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 817   28   86   24]
 [  26  853    0    0]
 [  47    0 2194    0]
 [ 140    0    0  781]]


In [23]:
GTcons = df_test['GTcons']
GTwithout = df_test['GTconswithoutIll300x.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 872   16   21   46]
 [   8  871    0    0]
 [  79    0 2162    0]
 [   9    0    0  912]]


In [24]:
GTcons = df_test['GTcons']
GTwithout = df_test['GTconswithoutIllMP.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 932    3   20    0]
 [   0  879    0    0]
 [   1    0 2240    0]
 [  10    0    0  911]]


In [25]:
GTcons = df_test['GTcons']
GTwithout = df_test['GTconswithoutTenX.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 883    2   68    2]
 [  14  865    0    0]
 [   1    0 2240    0]
 [  23    0    0  898]]


In [26]:
GTcons = df_test['GTcons']
GTwithout = df_test['GTconswithoutpacbio.GT']
print(confusion_matrix(GTcons, GTwithout))

[[ 618  192  100   45]
 [  91  788    0    0]
 [ 429    0 1812    0]
 [ 240    0    0  681]]


In [27]:
df_test['GTcons'].replace(-1, 'Unknown', inplace=True)
df_test['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_test['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_test['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_test['GTconswithoutIll250.GT'].replace(-1.0, 'Unknown', inplace=True)
df_test['GTconswithoutIll250.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_test['GTconswithoutIll250.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_test['GTconswithoutIll250.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout           -1    0     1    2   All
GTcons                                          
Heterozygous_Variant   429    0  1812    0  2241
Homozygous_Reference    91  788     0    0   879
Homozygous_Variant     240    0     0  681   921
Unknown                618  192   100   45   955
All                   1378  980  1912  726  4996

In [29]:
df_test['GTcons'].replace(-1, 'Unknown', inplace=True)
df_test['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_test['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_test['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_test['GTconswithoutIll300x.GT'].replace(-1.0, 'Unknown', inplace=True)
df_test['GTconswithoutIll300x.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_test['GTconswithoutIll300x.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_test['GTconswithoutIll300x.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout           -1    0     1    2   All
GTcons                                          
Heterozygous_Variant   429    0  1812    0  2241
Homozygous_Reference    91  788     0    0   879
Homozygous_Variant     240    0     0  681   921
Unknown                618  192   100   45   955
All                   1378  980  1912  726  4996

In [31]:
df_test['GTcons'].replace(-1, 'Unknown', inplace=True)
df_test['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_test['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_test['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_test['GTconswithoutIllMP.GT'].replace(-1.0, 'Unknown', inplace=True)
df_test['GTconswithoutIllMP.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_test['GTconswithoutIllMP.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_test['GTconswithoutIllMP.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout           -1    0     1    2   All
GTcons                                          
Heterozygous_Variant   429    0  1812    0  2241
Homozygous_Reference    91  788     0    0   879
Homozygous_Variant     240    0     0  681   921
Unknown                618  192   100   45   955
All                   1378  980  1912  726  4996

In [33]:
df_test['GTcons'].replace(-1, 'Unknown', inplace=True)
df_test['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_test['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_test['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_test['GTconswithoutTenX.GT'].replace(-1.0, 'Unknown', inplace=True)
df_test['GTconswithoutTenX.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_test['GTconswithoutTenX.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_test['GTconswithoutTenX.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout           -1    0     1    2   All
GTcons                                          
Heterozygous_Variant   429    0  1812    0  2241
Homozygous_Reference    91  788     0    0   879
Homozygous_Variant     240    0     0  681   921
Unknown                618  192   100   45   955
All                   1378  980  1912  726  4996

In [35]:
df_test['GTcons'].replace(-1, 'Unknown', inplace=True)
df_test['GTcons'].replace(0, 'Homozygous_Reference', inplace=True)
df_test['GTcons'].replace(1, 'Heterozygous_Variant', inplace=True)
df_test['GTcons'].replace(2, 'Homozygous_Variant', inplace=True)
df_test['GTconswithoutpacbio.GT'].replace(-1.0, 'Unknown', inplace=True)
df_test['GTconswithoutpacbio.GT'].replace(0.0, 'Homozygous_Reference', inplace=True)
df_test['GTconswithoutpacbio.GT'].replace(1.0, 'Heterozygous_Variant', inplace=True)
df_test['GTconswithoutpacbio.GT'].replace(2.0, 'Homozygous_Variant', inplace=True)
pd.crosstab(GTcons, GTwithout, rownames=['GTcons'], colnames=['GTconswithout'], margins=True)

GTconswithout         Heterozygous_Variant  Homozygous_Reference  \
GTcons                                                             
Heterozygous_Variant                  1812                     0   
Homozygous_Reference                     0                   788   
Homozygous_Variant                       0                     0   
Unknown                                100                   192   
All                                   1912                   980   

GTconswithout         Homozygous_Variant  Unknown   All  
GTcons                                                   
Heterozygous_Variant                   0      429  2241  
Homozygous_Reference                   0       91   879  
Homozygous_Variant                   681      240   921  
Unknown                               45      618   955  
All                                  726     1378  4996